### PR TITLE
#9: Add the "same region" requirement to docs (was only in examples).

### PR DESCRIPTION
**Pull request by kocielnik**
## What

- Adding the "same region" requirement to the description.

## Why

> `terraform-aws-vpc-peering` is for peering VPCs in the same account and the same region - see examples https://github.com/cloudposse/terraform-aws-vpc-peering/blob/master/examples/complete/main.tf

– https://github.com/cloudposse/terraform-aws-vpc-peering/issues/9#issuecomment-881493614

As suggested by Jake Naughton [^1] last September (2022), it can save some time for users browsing the documentation before they reach for the examples [^2].

[^1]: https://github.com/cloudposse/terraform-aws-vpc-peering/issues/9#issuecomment-1250178330
[^2]: https://github.com/cloudposse/terraform-aws-vpc-peering/issues/9#issuecomment-881493614

## References

1. #9

### CODE REVIEW

**Comment by kocielnik** [comment]
@jamengual, anything else I can do to make this good to merge?

If this change doesn't actually improve things, please let me know as well. Thanks!

**Review by jamengual — APPROVED** [review]

**Comment by kocielnik** [comment]
Closing due to inactivity.

**Pull request closed without merging**
